### ISSUE TITLE
PHP Fatal Error: Cannot redeclare debug()...

### ISSUE THREAD

**Issue by carywin** [jschildgen/ical4openhab#1]
I cloned the repo to my OpenHAB machine and put my iCAL link in the ical.php file.

When I run php ical.php DTSTART or DTEND I get the following error:
```
PHP Fatal error:  Cannot redeclare debug() (previously declared in /home/cary/ical4openhab/ical.php:228) in /home/cary/ical4openhab/ical.php on line 452
```
I have zero PHP experience, any help?

**Comment by jschildgen** [comment]
Hi, why does your ical.php has a line 452? Did you copy the code twice?

**Comment by carywin** [comment]
I don't know why, all I did initially was clone it to my OH machine /home dir.
This time I copied and pasted the code and it works.
